main/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth import views

from .views import *

urlpatterns = [
    path('', MainHome.as_view(), name='home'),
    path('catalog/', MainCatalog.as_view(), name='catalog'),
    path('payment/', payment, name='payment'),
    path('product/<slug:prod_slug>/', ShowProduct.as_view(), name='product'),
    path('product/<pk>/favorite/', login_required(FavoritesView.as_view()), name='favorite'),
    path('product/<pk>/cart/', login_required(CartView.as_view()), name='cart'),
    path('favorites/', login_required(FavoritesCatalog.as_view()), name='favorites'),
    path('cart/', login_required(CartPage.as_view()), name='cart_page'),
    path('exit/', views.LogoutView.as_view(), name='exit'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
]

sevita/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main.views import *
from sevita import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Product(models.Model):
    title = models.CharField(max_length=128, verbose_name='Заголовок')
    slug = models.SlugField(max_length=64, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(verbose_name='Описание')

    preview = models.ImageField(upload_to=f"images/preview/", verbose_name='Главное фото')
    on_hover = models.ImageField(upload_to=f"images/on_hover/", verbose_name='Фото при наведении')
    additional = models.ImageField(upload_to=f"images/additional/", verbose_name='Дополнительное фото', blank=True)

    low_price = models.CharField(max_length=32, default='', verbose_name='Цена за 2,5 мл')
    medium_price = models.CharField(max_length=32, default='', verbose_name='Цена за 5 мл')
    high_price = models.CharField(max_length=32, default='', verbose_name='Цена за 10 мл')

    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время обновления')
    is_visible = models.BooleanField(default=True, verbose_name='Видимость')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product', kwargs={'prod_slug': self.slug})

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Каталог'
        ordering = ['-time_create', 'title']


class Favorites(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    obj = models.ForeignKey(Product, verbose_name="Товар", on_delete=models.CASCADE)

    def __str__(self):
        return f'Парфюм "{self.obj}" в избранном пользователя {self.user}'

    class Meta:
        db_table = "favorites"
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'


class Cart(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    obj = models.ForeignKey(Product, verbose_name="Товар", on_delete=models.CASCADE)

    def __str__(self):
        return f'Парфюм "{self.obj}" в корзине пользователя {self.user}'

    class Meta:
        db_table = "cart"
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import *

CHOICES = (
    ("0", '2.5 мл'),
    ("1", '5 мл'),
    ("2", '10 мл')
)


class FeedBack(forms.Form):
    product = forms.ModelChoiceField(queryset=Product.objects.all(), label="Выберите парфюм", initial=0,
                                     widget=forms.Select(attrs={'class': "form__select"}))
    volume = forms.ChoiceField(choices=CHOICES, label="Выберите объём",
                               widget=forms.Select(attrs={'class': "form__select"}))
    contacts = forms.EmailField(label='Оставьте e-mail для связи:',
                                widget=forms.EmailInput(attrs={'class': "form__text",
                                                               'placeholder': 'your-email@email.ru'}))
    description = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'placeholder': 'Поле необязательно', 'class': 'form__text'}),
        label="Оставьте свои пожелания",
        required=False)


class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают!')
        return cd['password2']

main/views.py
import json

from django.contrib import auth
from django.http import HttpResponse, HttpResponseNotFound
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView

from .forms import *
from .models import *
from .utils import *
from .telegram import send_contacts


class MainHome(DataMixin, ListView):
    model = Product
    template_name = "main/index.html"
    context_object_name = 'products'

    def get_context_data(self, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="SEVITA exclusive", page="home")

        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        """
        Функция выводит только те объекты из базы данных, которые отмечены, как видимые и, так как это неполный каталог
        (каталог главной страницы), то устанавливает ограничение на количество выводимых объектов (count).
        """
        count = 8
        return Product.objects.filter(is_visible=True, pk__gte=Product.objects.count() - count + 1)


class MainCatalog(DataMixin, ListView):
    paginate_by = 12
    model = Product
    template_name = "main/catalog.html"
    context_object_name = 'products'

    def get_context_data(self, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Каталог", page="catalog")

        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        return Product.objects.filter(is_visible=True)


def payment(request):
    return HttpResponse('payment')


class ShowProduct(DataMixin, DetailView):
    model = Product
    template_name = 'main/product.html'
    slug_url_kwarg = 'prod_slug'
    context_object_name = 'prod'

    def get_context_data(self, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context['prod'], page="product", form=self.get_form(self.request))

        return dict(list(context.items()) + list(c_def.items()))

    # Сделать класс представления для этой формы и через {% include %} её подключить
    def get_form(self, request):
        if request.method == 'POST':
            form = FeedBack(request.POST)

            if form.is_valid():
                data = form.cleaned_data
                message_to_send = f"Товар: {data['product']}\nОбъём флакончика: {CHOICES[int(data['volume'])][1]}\n" \
                                  f"E-mail: {data['contacts']}\n"

                if data['description']:
                    message_to_send += f"Сообщение от отправителя: {data['description']}"
                try:
                    send_contacts(message_to_send)
                    return redirect('home')
                except:
                    form.add_error(None, "Ошибка отправки формы. Попробуйте позднее.")
        else:
            form = FeedBack()

        return form


def page_not_found(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


class RegisterUser(DataMixin, CreateView):
    form_class = UserRegistrationForm
    template_name = 'main/register.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация", page="register", form=self.reg(self.request))

        return dict(list(context.items()) + list(c_def.items()))

    def reg(self, request):
        if request.method == 'POST':
            user_form = UserRegistrationForm(request.POST)
            if user_form.is_valid():
                new_user = user_form.save(commit=False)
                new_user.set_password(user_form.cleaned_data['password'])

                new_user.save()
                return redirect('home')
        else:
            user_form = UserRegistrationForm()

        return user_form


# Добавление (удаление) в избранное
class FavoritesView(View):
    # В данную переменную будет устанавливаться модель избранного, которую необходимо обработать
    model = Favorites

    def post(self, request, pk):
        user = auth.get_user(request)

        # Пытаемся получить избранное из таблицы, или создать новую
        favorite, created = self.model.objects.get_or_create(user=user, obj_id=pk)

        # Если новый товар не добавлен в избранное, значит, он там уже есть, следовательно,
        # клик по этому товару будем считать запросом на удаление его из избранного
        if not created:
            favorite.delete()

        return HttpResponse(
            json.dumps({
                "result": created,
            }),
            content_type="application/json"
        )


# Добавление (удаление) в избранное
class CartView(View):
    # В данную переменную будет устанавливаться модель избранного, которую необходимо обработать
    model = Cart

    def post(self, request, pk):
        user = auth.get_user(request)

        # Пытаемся получить избранное из таблицы, или создать новую
        cart_item, created = self.model.objects.get_or_create(user=user, obj_id=pk)

        # Если новый товар не добавлен в избранное, значит, он там уже есть, следовательно,
        # клик по этому товару будем считать запросом на удаление его из избранного
        if not created:
            cart_item.delete()

        return HttpResponse(
            json.dumps({
                "result": created,
            }),
            content_type="application/json"
        )


class FavoritesCatalog(DataMixin, ListView):
    paginate_by = 12
    model = Product
    template_name = "main/favorites.html"
    context_object_name = 'products'

    def get_context_data(self, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Избранные", page="favorites")

        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        # Получаем текущего пользователя
        user = auth.get_user(self.request)

        # Получаем pk всех избранных
        fav_id = [i.obj.pk for i in Favorites.objects.filter(user=user)]
        return Product.objects.filter(pk__in=fav_id)


class CartPage(DataMixin, ListView):
    paginate_by = 12
    model = Product
    template_name = "main/cart.html"
    context_object_name = 'products'

    def get_context_data(self, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Корзина", page="cart_page")

        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        # Получаем текущего пользователя
        user = auth.get_user(self.request)

        # Получаем pk всех избранных
        cart_id = [i.obj.pk for i in Cart.objects.filter(user=user)]
        return Product.objects.filter(pk__in=cart_id)

main/templates/main/add_to_cart.html
{% load main_tags %}
{% load static %}

{% if user.is_authenticated %}
<script src="{% static 'main/js/ajax.js'%}"></script>
<div class="cart__block">
    <!--  Впишешь в верхний div какой-нибудь класс (либо оставь cart__block) и сделай для него позиционирование  -->
    <!--  В нижний класс (add-to-cart) добавь картнику на background. Класс в css уже создан. УБЕРИ ПОТОМ ЭТИ КОММЕНТАРИИ!  -->
    <button class="add-to-cart" data-type="{{ type }}"
         data-id="{{ prod.id }}" id="cart_{{ prod.id }}">Добавить в корзину
    </button>
</div>

<script>
    // Подключение обработчика
    $(function() {
        $('[id="cart_{{ prod.id }}"]').click(to_cart);
    });
</script>

{% endif %}

main/templates/main/add_to_favorites.html
{% load main_tags %}
{% load static %}

{% if user.is_authenticated %}
<script src="{% static 'main/js/ajax.js'%}"></script>
<div class="add__block">
    <div class="add-to-favorites {% if prod.favorites_set.all|user_in:user %}added{% endif %}" data-type="{{ type }}"
         data-id="{{ prod.id }}" id="fav_{{ prod.id }}"></div>
</div>

<script>
    // Подключение обработчика
    $(function() {
        $('[id="fav_{{ prod.id }}"]').click(to_favorites);
    });
</script>

{% endif %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'main/css/style.css'%}" rel="stylesheet">
    <link rel="icon" href="{% static 'main/img/favicons/icon.svg' type='image/svg+xml'%}">
</head>

<body>

<header class="header">
    <div class="wrapper">
        <div class="header__wrapper">
            <div class="header__logo">
                <a href="{% url 'home' %}" class="header__logo-link">
                    <img src="{% static 'main/img/logo.png'%}" alt="SEVITA exclusive" class="header__logo-pic">
                </a>
            </div>

            <nav class="header__nav">
                <ul class="header__list">
                    {% for item in header %}
                    {% if page == 'home' and item.title == 'О нас' %}
                    <li class="header__item">
                        <a href="#about" class="header__link">О нас</a>
                    </li>
                    {% elif not forloop.last %}
                    <li class="header__item">
                        <a href="{% url item.url_name %}" class="header__link">{{item.title}}</a>
                    </li>
                    {% else %}
                    <li class="header__item">
                        <a href="#contacts" class="header__link">Контакты</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </nav>

            <nav class="header__nav">
                <p class="header__profile">
                    <a href="#popup" class="header__profile-link">
                        <img src="{% static 'main/img/svg/profile.svg'%}" alt="Профиль" class="header__profile-pic">
                    </a>
                </p>
            </nav>
        </div>
    </div>
</header>

{% block content %}
{% endblock content %}


{% block footer %}
<p><a name="contacts"></a></p>
<section class="footer">
    <div class="wrapper">
        <div class="footer__wrapper">
            <div class="footer__div-logo">
                <img src="{% static 'main/img/logo.png'%}" alt="SEVITA exclusive" class="footer__logo">
            </div>
            <div class="footer__vk">
                <p class="footer__vk-desc">
                    По всем вопросам Вы можете написать в группу в ВК: <br>
                    <a href="https://vk.com/sevita_shop" class="vk-link" target="_blank">
                        <img src="{% static 'main/img/vk-logo.png'%}" alt="Написать нам" class="footer__vk-logo">
                    </a>
                </p>
            </div>
            <div class="footer__contacts">
                Контакты:<br><br>
                +7 9** *** **-**<br>
                your-email@email.ru
            </div>
        </div>
    </div>
</section>
{% endblock footer %}

<!--   Всплывающее окно авторизации/регистрации   -->
<div id="popup" class="popup">
    <a href="#header" class="popup__area"></a>
    <div class="popup__body">
        <div class="popup__content">
            <a href="#header" class="popup__close">X</a>
            {% if user.is_authenticated %}
            <h1>Привет, {{request.user.username}}!</h1>
            {% else %}
            <h1>Вход</h1>
            {% endif %}
            <div class="popup_wrapper">
                <div class="popup__form">
                    {% if user.is_authenticated %}
                    <p class="form_answer" style="text-align: center">Действия:<br><br>Корзина<br><br>Избранное<br></p>
                    <div class="form_btn">
                        <button class="btn new-margin_btn" type="submit"><a href="{% url 'exit' %}">Выход</a></button>
                    </div>
                    {% else %}
                    <div class="tabs">
                        <input type="radio" name="tab-btn" id="tab-btn-1" value="" checked>
                        <label for="tab-btn-1">Авторизация</label>
                        <input type="radio" name="tab-btn" id="tab-btn-2" value="">
                        <label for="tab-btn-2">Регистрация</label>

                        <div id="content-1">
                            <form method="post" action="{% url 'login' %}">
                                {% csrf_token %}

                                {% for f in login_form %}
                                <label for="{{ f.id_for_label }}" class="form_label">{{f.label}}: </label>
                                <p class="form_answer">{{ f }}</p>
                                <div class="form_error">{{ f.errors }}</div>
                                {% endfor %}
                                <div class="tabs-button">
                                    <button class="btn new-margin_btn" type="submit">Войти</button>
                                </div>
                            </form>
                        </div>
                        <div id="content-2">
                            {% include 'main/register.html' with registration_form=registration_form %}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

main/templates/main/cart.html
{%  extends 'main/base.html' %}

{% block content %}

{% include 'main/products_list.html' with products=products %}

<!--Тут нужны стили и надо обговорить, как мы будем выводить эти товары.-->

{% endblock %}

main/templates/main/catalog.html
{%  extends 'main/base.html' %}
{% load static %}
{% load main_tags %}

{% block content %}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<section class="catalog">
    <div class="wrapper">
        <div class="about__header">
            <a href="" class="about__pic"><img src="{% static 'main/img/svg/about-header.svg'%}" alt="sevita"
                                               class="about__header-pic"></a>
        </div>
        <div class="catalog__content">
            <div class="catalog__header">
                <h1>Каталог товаров</h1>
                <img src="{% static 'main/img/svg/delimiter-line.svg'%}" alt="delimiter" class="delimiter-line">
            </div>
            {% include 'main/products_list.html' with products=products %}

            {% if page_obj.has_other_pages %}
            <nav class="list-pages">
                <ul>
                    {% if page_obj.has_previous %}
                    <li class="page-num">
                        <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                    </li>
                    {% endif %}

                    {% for page in paginator.page_range %}
                    {% if page_obj.number == page %}
                    <li class="page-num page-num-selected">{{ page }}</li>
                    {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                    <li class="page-num">
                        <a href="?page={{ page }}">{{ page }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-num">
                        <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

main/templates/main/favorites.html
{%  extends 'main/base.html' %}

{% block content %}

{% include 'main/products_list.html' with products=products %}

<!--Тут нужны стили и надо обговорить, как мы будем выводить эти товары.-->

{% endblock %}

main/templates/main/index.html
{%  extends 'main/base.html' %}
{% load static %}
{% load main_tags %}

{% block content %}
<!--    Основное тело    -->
<main class="main">
    <!--   О нас   -->
    <section class="about">
        <div class="about_wrapper">
            <div class="about__header">
                <a href="" class="about__pic"><img src="{% static 'main/img/svg/about-header.svg'%}" alt="sevita"
                                                   class="about__header-pic"></a>
                <p><a name="about"></a></p>
            </div>

            <div class="about__content">
                <img src="{% static 'main/img/about-pic.png'%}" alt="About" class="about__content-pic" align="middle">
                <div class="about__content-description">
                    <h1>О проекте</h1>
                    <img src="{% static 'main/img/svg/delimiter-line.svg'%}" alt="delimiter" class="delimiter-line">
                    Нишевый парфюм — достаточно редкая история: его практически не купишь в популярных косметических
                    магазинах и мало на ком встретишь. А еще ниша дорого стоит, и отдать состояние за флакон, который
                    может разонравиться — довольно обидно.<br>
                    Чтобы вы не тратили деньги зря и искали новые ароматы с удовольствием, мы предлагаем распив —
                    миниатюры самого разного нишевого парфюма. Вы можете приобрести абсолютно любой аромат в объёме от
                    5мл, разносить его в любую погоду, в любом настроении, на разные мероприятия.
                </div>
            </div>
        </div>
    </section>

    <!--   Часто задаваемые вопросы   -->
    <section class="questions">
        <script src="https://snipp.ru/cdn/jquery/2.1.1/jquery.min.js"></script>
        <script src="https://snipp.ru/cdn/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script src="{% static 'main/js/scripts.js'%}"></script>

        <div class="wrapper">
            <div class="qa__wrapper">
                <div class="questions__content">
                    <h1>Часто задаваемые вопросы</h1>
                    <img src="{% static 'main/img/svg/delimiter-line.svg'%}" alt="delimiter" class="delimiter-line">
                    <div class="questions-answers">
                        <div class="accordion">
                            <div class="accordion-item">
                                <div class="accordion-header">
                                    <h2>1. Что такое распив?</h2>
                                </div>
                                <div>
                                    <p class="answer">Распив - это когда парфюм из большого оригинального флакона
                                        переносится в другой - специальный, новый, чистый- флакончик меньшего
                                        объёма.</p>
                                </div>
                            </div>

                            <div class="accordion-item">
                                <div class="accordion-header">
                                    <h2>2. Что такое атом/атомайзер?</h2>
                                </div>
                                <div>
                                    <p class="answer">Это тот самый специальный флакончик меньшего объёма, куда
                                        переносится парфюм. Доступный объем атомайзеров у меня: 5, 10, 18, 30мл.</p>
                                </div>
                            </div>

                            <div class="accordion-item">
                                <div class="accordion-header">
                                    <h2>3. Что такое отливант?</h2>
                                </div>
                                <div>
                                    <p class="answer">Это готовый маленький флакончик (атомайзер) с парфюмом, отлитый из
                                        большого оригинального фирменного флакона, которым вы можете с удовольствием
                                        пользоваться. На каждом отливанте есть наклейка с названием вашего аромата.</p>
                                </div>
                            </div>

                            <div class="accordion-item">
                                <div class="accordion-header">
                                    <h2>4. Как долго я смогу им пользоваться?</h2>
                                </div>
                                <div>
                                    <p class="answer">1мл - это около 10-15 пшиков в зависимости от аромата
                                        (направления, концентрации,...) и ваших привычек. 2мл хватает примерно на 1
                                        неделю активного использования, 5мл хватает примерно на месяц, 10мл на 2-3
                                        месяца.</p>
                                </div>
                            </div>

                            <div class="accordion-item">
                                <div class="accordion-header">
                                    <h2>5. У вас точно оригинал?</h2>
                                </div>
                                <div>
                                    <p class="answer">Да, у меня точно оригинал) У меня проверенные годами поставщики.
                                        Да и те редкие нишевые ароматы, которые я вам предлагаю, их просто не
                                        подделывают.</p>
                                </div>
                            </div>

                            <div class="accordion-item">
                                <div class="accordion-header">
                                    <h2>6. Почему именно наш магазин?</h2>
                                </div>
                                <div>
                                    <p class="answer">Я познакомлю вас с новыми брендами, направлениями, с редкими
                                        интересными ароматами. Помогу в спокойной обстановке подобрать аромат с учетом
                                        ваших пожеланий и потребностей. При этом вам не придётся тратить десятки/сотни
                                        тысяч рублей для знакомства с парфюмом и поиска своего идеального аромата!)</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--   Каталог товаров   -->
    <section class="catalog">
        <div class="wrapper">
            <div class="catalog__content">
                <div class="catalog__header">
                    <h1>Каталог товаров</h1>
                    <img src="{% static 'main/img/svg/delimiter-line.svg'%}" alt="delimiter" class="delimiter-line">
                </div>
                {% include 'main/products_list.html' with products=products %}
            </div>
        </div>
        <div class="watch-more">
            <a href="{% url 'catalog' %}" class="catalog__watch-more">Посмотреть весь каталог...</a>
        </div>
    </section>
</main>
{% endblock %}

main/templates/main/product.html
{%  extends 'main/base.html' %}
{% load static %}

{% block content %}

<section class="product">
    <div class="wrapper">
        <!--  Header  -->
        <div class="about__header">
            <a href="" class="about__pic">
                <img src="{% static 'main/img/svg/about-header.svg'%}" alt="sevita" class="about__header-pic">
            </a>
        </div>
    </div>


    <!--  Product  -->
    <div class="wrapper">
        <div class="product__wrapper">
            <div class="product__photos">
                {% if prod.preview %}
                <img src="{% static 'main/img/left.png'%}" alt="left_arrow" class="arrow left limit"><!--
                --><img src="{{prod.preview.url}}" alt="{{prod.title}}" class="product__preview active"><!--
                --><img src="{{prod.on_hover.url}}" alt="{{prod.title}}" class="product__preview"><!--
                --><img src="{{prod.additional.url}}" alt="{{prod.title}}" class="product__preview"><!--
                --><img src="{% static 'main/img/right.png'%}" alt="right_arrow" class="arrow right">
                {% endif %}
            </div>
            <div class="product_description">
                <p class="product__title">{{prod.title}}</p>
                <p class="product__volume">Выберите объём:</p>
                <script src="{% static 'main/js/scripts.js'%}"></script>
                <div class="product__buttons">
                    <button id="2.5ml" class="btn" onclick="setPrice({{prod.low_price}}, '2.5ml')" disabled>2,5 мл
                    </button>
                    <button id="5ml" class="btn" onclick="setPrice({{prod.medium_price}}, '5ml')">5 мл</button>
                    <button id="10ml" class="btn" onclick="setPrice({{prod.high_price}}, '10ml')">10 мл</button>
                </div>
                <p class="prod__price" id="price">Цена: {{prod.low_price}} руб.</p>
                <p class="prod__desc">{{prod.content|linebreaks}}</p>


            </div>

            <div class="product__feedback">
                <p class="product__fbheader">Вы можете оставить заявку на покупку, заполнив форму ниже:</p>
                <div class="form__wrapper">
                    <form action="" method="post">
                        {% csrf_token %}

                        <div class="form_error">{{ form.non_field_errors }}</div>

                        {% for f in form %}
                        <label for="{{ f.id_for_label }}" class="form_label">{{f.label}}: </label>
                        <p class="form_answer">{{ f }}</p>
                        <div class="form_error">{{ f.errors }}</div>
                        {% endfor %}

                        <div class="form_btn">
                            <button class="btn new-margin_btn" type="submit">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <script src="{% static 'main/js/slider.js'%}"></script>
</section>
{% endblock %}